DROP SEQUENCE Store_seq;
DROP SEQUENCE Coffee_seq;
DROP SEQUENCE Promotion_seq;
DROP SEQUENCE MemberLevel_seq;
DROP SEQUENCE Customer_seq;
DROP SEQUENCE Purchase_seq;


CREATE SEQUENCE Store_seq
	MINVALUE 1
	MAXVALUE 9999999
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE Coffee_seq
	MINVALUE 1
	MAXVALUE 9999999
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE Promotion_seq
	MINVALUE 1
	MAXVALUE 9999999
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE MemberLevel_seq
	MINVALUE 1
	MAXVALUE 9999999
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE Customer_seq
	MINVALUE 1
	MAXVALUE 9999999
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE Purchase_seq
	MINVALUE 1
	MAXVALUE 9999999
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

